language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew check
post:
  - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
after_success:
  - bash <(curl -s https://codecov.io/bash)